version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - "5000:80"
    env_file: .env.production
    restart: unless-stopped
