services:
  front:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    volumes:
      - "./api:/api"
      - "api_node_modules:/api/node_modules"
      - "data:/data"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/data/data.db
    command: sh -c "npm install && npx prisma migrate dev --name init && npm run dev"
    
volumes:
  node_modules:
  api_node_modules:
  data:
