version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - "5000:80"
    env_file: .env.production
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: api
    env_file: .env.production
    volumes:
      - data:/data
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && node server.js"

volumes:
  data:
