version: "3.9"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - "./dist:/usr/share/nginx/html:ro"
    labels:
      - "coolify.enabled=true"
      - "traefik.enable=true"
      - "traefik.http.routers.lumieres.rule=Host(`lumieres.mondomaine.xyz`)"
      - "traefik.http.routers.lumieres.entrypoints=websecure"
      - "traefik.http.routers.lumieres.tls.certresolver=letsencrypt"
      - "traefik.http.services.lumieres.loadbalancer.server.port=80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    volumes:
      - "data:/data"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/data.db
      - PORT=4000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lumieres-api.rule=Host(`lumieres-api.mondomaine.xyz`)"
      - "traefik.http.routers.lumieres-api.entrypoints=websecure"
      - "traefik.http.routers.lumieres-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.lumieres-api.loadbalancer.server.port=4000"
    command: sh -c "npx prisma migrate deploy && npm start"
    restart: unless-stopped

volumes:
  data:
    driver: local
