services:
  app-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: flask-todo-prod
    volumes:
      - ./instance:/app/instance
    ports:
      - "${PORT}:${PORT}"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_APP=src/app.py
      - PORT=${PORT}
      - PYTHONPATH=/app
    restart: unless-stopped
